/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root/route";
import { Route as SplatRouteRouteImport } from "./routes/$/route";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as PublicRouteRouteImport } from "./routes/_public/route";
import { Route as AuthenticatedIndexRouteRouteImport } from "./routes/_authenticated/index/route";
import { Route as AuthenticatedDashboardRouteRouteImport } from "./routes/_authenticated/dashboard/route";
import { Route as PublicForgotPasswordRouteRouteImport } from "./routes/_public/forgot-password/route";
import { Route as PublicLoginRouteRouteImport } from "./routes/_public/login/route";
import { Route as PublicSignUpRouteRouteImport } from "./routes/_public/sign-up/route";

const SplatRouteRoute = SplatRouteRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRouteRoute = AuthenticatedIndexRouteRouteImport.update({
  id: "/",
  path: "",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedDashboardRouteRoute = AuthenticatedDashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const PublicForgotPasswordRouteRoute = PublicForgotPasswordRouteRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicLoginRouteRoute = PublicLoginRouteRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicSignUpRouteRoute = PublicSignUpRouteRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => PublicRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/$": typeof SplatRouteRoute;
  "/": typeof AuthenticatedIndexRouteRoute;
  "/dashboard": typeof AuthenticatedDashboardRouteRoute;
  "/forgot-password": typeof PublicForgotPasswordRouteRoute;
  "/login": typeof PublicLoginRouteRoute;
  "/sign-up": typeof PublicSignUpRouteRoute;
}
export interface FileRoutesByTo {
  "/$": typeof SplatRouteRoute;
  "/": typeof AuthenticatedIndexRouteRoute;
  "/dashboard": typeof AuthenticatedDashboardRouteRoute;
  "/forgot-password": typeof PublicForgotPasswordRouteRoute;
  "/login": typeof PublicLoginRouteRoute;
  "/sign-up": typeof PublicSignUpRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/$": typeof SplatRouteRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/_public": typeof PublicRouteRouteWithChildren;
  "/_authenticated/": typeof AuthenticatedIndexRouteRoute;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRouteRoute;
  "/_public/forgot-password": typeof PublicForgotPasswordRouteRoute;
  "/_public/login": typeof PublicLoginRouteRoute;
  "/_public/sign-up": typeof PublicSignUpRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/$" | "/" | "/dashboard" | "/forgot-password" | "/login" | "/sign-up";
  fileRoutesByTo: FileRoutesByTo;
  to: "/$" | "/" | "/dashboard" | "/forgot-password" | "/login" | "/sign-up";
  id:
    | "__root__"
    | "/$"
    | "/_authenticated"
    | "/_public"
    | "/_authenticated/"
    | "/_authenticated/dashboard"
    | "/_public/forgot-password"
    | "/_public/login"
    | "/_public/sign-up";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  SplatRouteRoute: typeof SplatRouteRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public": {
      id: "/_public";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PublicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_public/forgot-password": {
      id: "/_public/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof PublicForgotPasswordRouteRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    "/_public/login": {
      id: "/_public/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof PublicLoginRouteRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    "/_public/sign-up": {
      id: "/_public/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof PublicSignUpRouteRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRouteRoute: typeof AuthenticatedIndexRouteRoute;
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRouteRoute: AuthenticatedIndexRouteRoute,
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
};

const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

interface PublicRouteRouteChildren {
  PublicForgotPasswordRouteRoute: typeof PublicForgotPasswordRouteRoute;
  PublicLoginRouteRoute: typeof PublicLoginRouteRoute;
  PublicSignUpRouteRoute: typeof PublicSignUpRouteRoute;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicForgotPasswordRouteRoute: PublicForgotPasswordRouteRoute,
  PublicLoginRouteRoute: PublicLoginRouteRoute,
  PublicSignUpRouteRoute: PublicSignUpRouteRoute,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(PublicRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  SplatRouteRoute: SplatRouteRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
